---
title: "Writing Functions"
author: "Xiaoni Xu"
date: "2024-10-24"
output: github_document
---
```{r, message = FALSE}
library(tidyverse)
library(rvest)
library(readxl)
```

## writing the first function

as an example, htere's a z-score computation

```{r}
x_vec = rnorm(n = 25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Now I'll write a function to do this

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("x needs to be numeric")
  }
  
  if (length(x) <5 ) {
    stop("you need at least five numbers to compute z score")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x = x_vec)
```

Does this always work?
```{r, error = TRUE}
z_scores(x = 3)

z_scores(x = c("my", "name", "is", "xiaoni"))

z_scores(x = x_vec)
```

## A new function

```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(out_df)
}

mean_and_sd(x_vec)
```

## Check stuff using a simulation

```{r}
sim_mean_sd = function(samp_size, true_mean, true_sd){
  # default values: samp_size = .., true_mean = ..., true_sd = ...
  # able to overwrite with `sim_mean_sd(30,16,2)`
  sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )
  
  out_df = 
    sim_df %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
  
  return(out_df)
}

sim_mean_sd(samp_size = 30000, true_mean = 4, true_sd = 12)

sim_mean_sd(30,16,2)

```

## Revisit LoTR words

```{r}
fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship") %>% 
  janitor::clean_names()

two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers") %>% 
  janitor::clean_names()

return_king_df = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king") %>% 
  janitor::clean_names()
```


Let's do this using a function instead.
```{r}
lotr_import = function(cell_range, movie_title){
  
  movie_df = 
    read_excel("data/LotR_Words.xlsx", range = cell_range) %>% 
    mutate(movie = movie_title) %>% 
    janitor::clean_names() %>% 
    pivot_longer(
      female:male,
      names_to = "sex", 
      values_to = "words"
    ) %>% 
    select(movie, everything())
  
  return(movie_df)
}


lotr_import(cell_range = "B3:D6", movie_title = "fellowship")
lotr_import("F3:H6", "two towers")
lotr_import("J3:L6", "return_king")

lotr_df = 
  bind_rows(
    lotr_import("B3:D6", "fellowship"),
    lotr_import("F3:H6", "two towers"),
    lotr_import("J3:L6", "return_king")
  )


```

## NSDUH data
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

nsduh_import = function(html, nth, drug_name){
  
  drug_table = 
    html %>% # just so that html is included but not outside of the environment
    html_table() %>% 
    nth(nth) %>% 
    slice(-1) %>% 
    mutate(drug = drug_name)
  
  return(drug_table)
  
}

nsduh_import(html = nsduh_html, 1, "marj")

nsduh_df = 
  bind_rows(
    nsduh_import(html = nsduh_html, 1, "marj"),
    nsduh_import(html = nsduh_html, 4, "cocaine"),
    nsduh_import(html = nsduh_html, 5, "heroin")
  )

# it runs! it runs! i'm a genius

marj_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(1) %>% 
  slice(-1) %>% 
  mutate(drug = "marj")

cocaine_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(4) %>% 
  slice(-1) %>% 
  mutate(drug = "cocaine")

heroin_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(5) %>% 
  slice(-1) %>% 
  mutate(drug = "heroin")
```

